services:
  faster-whisper-loader:
    platform: linux/amd64
    build:
      context: faster
      dockerfile: Dockerfile.loader
    container_name: faster-whisper-loader
    entrypoint: /bin/sh -c 'python load_models.py'
    volumes:
      - ./faster/models:/app/models

  faster-whisper:
    platform: linux/amd64
    build: faster
    container_name: faster-whisper
    ports:
      - "10300:5000"
    volumes:
      - ./faster/uploads:/app/uploads
      - ./faster/models:/app/models
    restart: unless-stopped
    depends_on:
      - faster-whisper-loader


  app:
    platform: linux/amd64
    build: ui
    ports:
      - "8080:80"
    container_name: app
    depends_on:
      - faster-whisper