services:
  faster-whisper-loader:
    platform: linux/amd64
    build:
      context: faster
      dockerfile: Dockerfile.loader
    container_name: faster-whisper-loader
    entrypoint: /bin/sh -c 'python load_models.py'
    volumes:
      - ./faster/models:/app/models

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    restart: unless-stopped
    networks:
      - isolated

  faster-whisper:
    platform: linux/amd64
    build: faster
    container_name: faster-whisper
    ports:
      - "10300:5000"
    volumes:
      - ./faster/uploads:/app/uploads
      - ./faster/models:/app/models
      - ./faster/transcriptions:/app/transcriptions
    restart: unless-stopped
    networks:
      - isolated
    depends_on:
      - mongo
      - faster-whisper-loader


  app:
    platform: linux/amd64
    build: ui
    ports:
      - "8080:80"
    container_name: app
    restart: unless-stopped
    networks:
      - net
      - isolated
    depends_on:
      - faster-whisper

networks:
  isolated:
    internal: true
  net:
    driver: bridge